name: Main Build
on:
  push:
    branches:
      - main
      - release/**
    paths-ignore:
      - stacks/sysadmin/**
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: tf

jobs:
  apply:
    uses: curioswitch/cdktf-actions/.github/workflows/main.yaml@c58ab526bff81207e69e2e94061b630baa67edf3
    with:
      gcp_project_id: ${{ startsWith(github.ref_name, 'release/') && 'cookchat-prod' || 'cookchat-dev'}}
      gcp_project_number: ${{ startsWith(github.ref_name, 'release/') && '623397668020' || '408496405753'}}
